global using Force.DeepCloner;
global using FluentValidation;
global using FluentValidation.Internal;
global using LazyMagic.Client.Base;
global using LazyMagic.Shared;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Logging;
global using Newtonsoft.Json;
global using ReactiveUI;
global using ReactiveUI.Fody.Helpers;
global using System.ComponentModel;
global using System.Collections.Specialized;
global using System.Reactive.Linq;
global using System.Reactive.Disposables;
global using System.Reflection;
global using System.Threading.Tasks;

