<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)CommonPackageHandling.targets" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>

		<Description>LazyMagic Blazor SVG ViewModels and Models</Description>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>

		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>


</Project>
