global using Blazorise;
global using Blazorise.Components;
global using Blazorise.Bootstrap5;
global using Blazorise.Extensions;
global using Blazorise.Modules;
global using Microsoft.AspNetCore.Components;
global using Microsoft.JSInterop;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
